### ISSUE TITLE
[TASK] Update type-scale and confirmation cards

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1027]
## Overview

As per the team's feedback, we need to update the typescale for input fields items on the bridge control cards. The updated heading 5 (20px) has been added to the design system to accommodate this change. As a result, the input fields need to be updated from body1 (16px), which was too small for visibility.

However, this update will create a collateral change in the confirmation and transaction progress screens, as the content will go out of bound of the control cards' length (700px). Therefore, we need to update the aforementioned screens to ensure that the content stays within bounds.

The proposed solution is to remove the chain diagram, which takes up a lot of space. This will enable us to retain all the important information for confirming the transactions in deposit, transfer, and withdrawal. The detailed updated changes have been documented below: 

### [End-to-End Wireframes ](https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?node-id=940%3A139772&t=e2URdXHVXlFtU6aj-1)
Please refer to the latest updated wireframes for the update to typescale & confirmation screens. You may also view the prototype [here](https://www.figma.com/proto/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?page-id=940%3A139772&node-id=2460%3A469924&viewport=-5536%2C3856%2C0.64&scaling=scale-down&starting-point-node-id=2460%3A469400&show-proto-sidebar=1). 

![Screenshot 2023-02-28 at 12 03 26 PM](https://user-images.githubusercontent.com/109539270/221966064-3c4d9436-cf01-485b-b0ea-470b99d1e5be.png)

### Changes
- [x] All input headings have been updated to `Body01 BOLD`
- [x] All input items have been updated to `H5 BOLD`
- [x] All fee details have been updated to `Body01 BOLD`
- [x] Chain and Token list selection: Token and Chain Symbol `H5 BOLD`; Token and Chain Name `Body01 BOLD`
- [ ] Confirmation Screens have been updated in Deposit, Transfer, and Withdrawal (refer to wireframe)
- [ ] Update storybook and `webb-ui-component` library

![Screenshot 2023-02-28 at 11 54 41 AM](https://user-images.githubusercontent.com/109539270/221964313-efc2464b-e9d9-46d9-8c00-656fdee307be.png)
- [ ] To accommodate for this update, added chain chips in the [design system](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=55%3A8673&t=ZGm88FJbAgtMOqy9-1) (found in the page **'🟢  Chips'**)

![Screenshot 2023-02-28 at 11 58 32 AM](https://user-images.githubusercontent.com/109539270/221965052-7d4e5488-ea87-40df-906a-39bbb0eb9200.png)

**Comment by dutterbutter** [comment]
@monaiuu the space in the deposit / withdraw is a lot. Is that intentional? 

![mona](https://user-images.githubusercontent.com/29983536/227270222-8908730a-4ab9-4a14-8bea-c3501808211f.png)

**Comment by monaiuu** [comment]
> @monaiuu the space in the deposit / withdraw component is a lot. Is that intentional?
> 
> ![mona](https://user-images.githubusercontent.com/29983536/227270222-8908730a-4ab9-4a14-8bea-c3501808211f.png)

Hey @dutterbutter @devpavan04, please see below for the updated components as mentioned above. It can be referenced in the design system within the page "Inputs". 
<img width="2165" alt="Screenshot 2023-03-23 at 2 46 23 PM" src="https://user-images.githubusercontent.com/109539270/227372260-2e0ad727-e82f-4ae7-af1a-c3d6d4347129.png">

These components have also been updated in the upcoming version of the end-to-end wireframe/prototype integrating the Stats UI widget. I will update the above links in this issue once it is closed for completion. 

<img width="1069" alt="Screenshot 2023-03-23 at 2 50 55 PM" src="https://user-images.githubusercontent.com/109539270/227372795-33f40ef4-256b-4318-a960-5fabafc97f72.png">
<img width="876" alt="Screenshot 2023-03-23 at 2 51 07 PM" src="https://user-images.githubusercontent.com/109539270/227372807-d3ba9e4e-2300-4835-bfd7-a29548ef375b.png">
<img width="768" alt="Screenshot 2023-03-23 at 2 51 20 PM" src="https://user-images.githubusercontent.com/109539270/227372851-1177c2bb-06ae-497c-b15b-7bb19c8cfa14.png">


_(I intend on better organizing these bridge card  input components in the near future, apology for the mess for now; as I believe these should be local components rather than global components as they currently are)_

**Comment by monaiuu** [comment]
Just went through the deployed preview, I noticed in the deposit & transfer bridge card, the title of the `amount` input is missing (see below). 

<img width="552" alt="Screenshot 2023-03-23 at 3 21 40 PM" src="https://user-images.githubusercontent.com/109539270/227391672-c7742344-51e8-4f28-b48f-8c4f1e83e3de.png"> 

I think we should add the amount title back to the input to ensure consistency. Below is a screenshot from the withdrawal card:
<img width="552" alt="Screenshot 2023-03-23 at 3 22 24 PM" src="https://user-images.githubusercontent.com/109539270/227392014-4933e86a-f90a-496d-b72e-1196075f0fc8.png">
