### ISSUE TITLE
[TASK] Adjustments to Blog page

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1041]
## Overview

This task describes the improvements to be made to the Blog page prior to deployment to prod. 

### Task Checklist

1. Dedicated 'Research' tag for posts that essentially just link to a research paper
2. Using the distinct 'Research' tag we want to simply display a card that will link directly to the paper (e.g. similar to aztec - https://aztec.network/research-and-talks)
3. Update video images to be more Webb branded 

@monaiuu could you please provide improved images for the video thumbnails. You can view the existing images [here](https://staging.webb.tools/blog). Some inspiration could be the following:

![CleanShot 2023-03-08 at 08 22 47](https://user-images.githubusercontent.com/29983536/223737906-be1e40ef-fb3b-49b9-8792-ffd6e8761da3.png)

**Comment by monaiuu** [comment]
### Quick Updates to Blog Page

Based on discussion with @devpavan04, made some minor improvements to the Webb Blog to address some of the issues brought up:

- Add `utility button` to the featured card so that user knows what type of content it will redirect. (For Papers -> `Read Paper`; for Blog Posts -> `Read Post`)
- Update subheading from **Recent Videos** to **Featured**, update heading from **Writing by Topic** to **Writings**, and **Videos by Topic** to **Medias and Press**.
- For all writing cards, add `chips` to identify the type of content. 
- Add headinga to the video cards (Talk, Tutorial, Community) to address consistency w/ above cards.

### Screenshot
<img width="738" alt="Screenshot 2023-03-08 at 2 25 30 PM" src="https://user-images.githubusercontent.com/109539270/223865752-d8ae486e-cc83-4bd1-b735-f55a1cb5190d.png">

Hopefully, some of these changes address the issues mentioned. If you see anything else that can be improved, please let me know! @devpavan04 

I am still working on generating a range of blog post graphics that are on-brand so we can use them for all our current/future posts. Will let you know once completed.
