### ISSUE TITLE
[TASK] Improve responsive breakpoints for Hubble bridge

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1085]
## Handoff

The responsive breakpoints for the Bridge DApp have been completed and are ready for implementation. The breakpoints define screen sizes for a consistent & optimized user experience.  At each breakpoint, the site adapts its layout to better fit the available screen space to display the most important components. 

### Notes:

- At the `480px` breakpoint, the layout switches to a one-column layout displaying only the bridge control card.
- Selective table items will be hidden as interface hits smaller breakpoints (reference below)
- Add `mobile footer component` to webb UI Kit (webb storybook), this component should be reusable across the dapp system

### Handoff Wireframes
Can be found in the page 🛠 **Responsive Breakpoints** within the **🌉  Bridge UI v1** Figma File.
https://www.figma.com/file/35GtMH3QSbmmCpV7ddSZZu/%F0%9F%8C%89--Bridge-UI-v1?node-id=2967%3A361717&t=HvZSPkhfKBciJzgP-1

### Screen Recording

https://user-images.githubusercontent.com/109539270/228069800-5b6c1d08-b7cb-49bc-adf4-92f177a29414.mp4

**Comment by vutuanlinh2k2** [comment]
@drewstone I find this issue quite familiar with the [one](https://github.com/webb-tools/webb-dapp/issues/954) I'm working on (shows a layout of 1 column with only the control card on mobile), and it seems the chart on the left side, and the table below are not implemented yet. Should we postpone this issue until later?

**Comment by drewstone** [comment]
No we shouldn't postpone. Please meet with @monaiuu to ensure it all gets completed. Since mobile isn't functional we don't need to show things like the note table if that's what you're referring to. I'm not sure what chart is being referenced here either so please be a bit more descriptive and use images if necessary.

**Comment by drewstone** [comment]
If there are things not implemented in design don't worry yet. This task is primarily about mobile responsiveness.

**Comment by monaiuu** [comment]
> @drewstone @AtelyPham I find this issue quite familiar with the [one](https://github.com/webb-tools/webb-dapp/issues/954) I'm working on (shows a layout of 1 column with only the control card on mobile), and it seems the chart on the left side, and the table below are not implemented yet. Should we postpone this issue until later?

Yes, there are similarities with the issue #954, with the key difference being #954 is the view on mobile devices (requiring our system to detect - i.e., user agent strings), whereas this issue is adding tablet & mobile breakpoints when viewing on desktop.

The table component in this issue should be implemented, whereas the table component is not applicable on mobile devices since users cannot transact/connect their wallet on mobile devices yet. So don't worry about implementing the table component for issue #954. 

The stats graph component on the left side of the video above should be addressed in a separate issue once finalized. Since we are currently working on hubble bridge V2, as mentioned by @drewstone, don't worry about the stats graph component for this issue, as this issue's goal is on implementing the different breakpoints.

@vutuanlinh2k2 I hope I have addressed all the questions. Let me know if there is something unclear!

**Comment by vutuanlinh2k2** [comment]
@monaiuu, just one last check before I start working on this task. Since the Bridge is currently having the **main component (Deposit, Transfer, Withdraw)** on the left and the User Guide on the right side, the goal here is just to make the UI only show the **main component** when users reach tablet & mobile breakpoints when viewing on desktop devices, right?

Current Bridge:

<img width="1440" alt="Screenshot 2023-06-07 at 21 52 34" src="https://github.com/webb-tools/webb-dapp/assets/69841784/14aa9e7a-8b3a-456b-9112-12f2b3995011">

**Comment by drewstone** [comment]
I think you are correct @vutuanlinh2k2, we should just focus the main component, you don't need to worry about the education component on the smaller screens.
