### ISSUE TITLE
[TASK] Updates needed for Tangle website 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#1192]
**General:** 
- Remove or otherwise disable crowdloan purple banner.  (May need in future)

<img width="1669" alt="Screenshot 2023-05-11 at 10 58 44 AM" src="https://github.com/webb-tools/webb-dapp/assets/38070512/c46ca48f-4638-4826-b141-23abfde490e0">
Note for @monaiuu , we're not using folds super well. Modules are taller than fits in single screen heights, and so scrolling is awkward and breaks up information that should otherwise be seen as a complete module.

**The TSS section is interesting, we should give it its own explanatory section with several benefits, a quick draft of that text would look like this:**

```
TSS
Enhance your digital security with threshold signature schemes. Say goodbye to single points of failure and key compromises. With distributed signing authority, your assets remain protected against unauthorized access and insider attacks.

Resilience in Adversity:
Safeguard your operations with threshold signatures. Even if some participants are unavailable or act maliciously, a sufficient threshold ensures secure signing. Trust that your critical applications will continue to function smoothly.

Preserve Your Privacy: 
Protect sensitive information with threshold signature schemes. Your signing authority is separate from individual signers, ensuring privacy. Transact confidently without compromising personal data.

Scale with Confidence: 
Unlock scalability and availability in distributed systems. Leverage the combined power of multiple entities. With a threshold of participants, your system can handle increased demands while ensuring availability.

Minimize Trust, Maximize Control: 
Reduce dependence on trust with threshold signatures. Distribute signing authority to minimize risks. Maintain control over your digital world with confidence.
```

<img width="1120" alt="Screenshot 2023-05-11 at 11 05 17 AM" src="https://github.com/webb-tools/webb-dapp/assets/38070512/2c9ac61f-c2aa-4569-b5c5-588f3da2282c">
Remove the highlighted text.

<img width="1152" alt="Screenshot 2023-05-11 at 11 06 05 AM" src="https://github.com/webb-tools/webb-dapp/assets/38070512/ea50f554-b8c0-4a53-b001-448219bbb411">

- Remove the highlighted text.
- Additionally, would be good to re-balance icon sizing and spacing for this section.  Lots of negative space in the Icon. ICon should probably sit left of the header text rather than on new line.
- Change use case text:

```
General Messaging Passing & Public Bridges: 
Seamlessly facilitate public and transparent cross-chain interactions. Experience unparalleled efficiency and security through a dynamic TSS-based system, where multiple participants collaborate harmoniously.

Connected Shielded Pool Protocols: 
Unleash the true potential of interconnected ecosystems to empower private movement and the seamless transfer of assets between blockchains. Unleash the true potential of interconnected ecosystems.

Connected Shielded Identity Protocols: 
Harness the revolutionary privacy of the Network to forge identities and establish meaningful connections between diverse blockchains. Bridge the gaps and unite digital realms like never before.

Oracle System and Data Feeds: 
Empower financial, identity, and other applications with trustworthy information through the next-gen Webb DKG (Distributed Key Generation) to securely sign payloads from data feeds. 
```

<img width="941" alt="Screenshot 2023-05-11 at 11 18 47 AM" src="https://github.com/webb-tools/webb-dapp/assets/38070512/ebad9305-ff16-4306-b748-7a74eb405ba0">

- The bulletpoints are not being rendered here.

<img width="1163" alt="Screenshot 2023-05-11 at 11 19 29 AM" src="https://github.com/webb-tools/webb-dapp/assets/38070512/52e8bd1c-fe8c-4b75-a54c-baf31b022e07">

- Remove the highlighted text.

<img width="290" alt="Screenshot 2023-05-11 at 11 19 53 AM" src="https://github.com/webb-tools/webb-dapp/assets/38070512/9bcc9f53-a717-47bf-8d69-adc3427d5b89">

- Remove this text at footer.

**Comment by monaiuu** [comment]
### Description
I would like to add in a few more UI improvements before we finalize Tangle Website for launch. Please reference Figma File for reference on the updates:

- [ ] Ensure background image is _repeated vertically_ in order to render image behind the required sections throughout the page in smaller breakpoints with longer heights. <img width="678" alt="Screenshot 2023-05-23 at 4 06 32 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/ffb0ff60-1fb6-4b49-b168-070f5f889be1">


- [ ] Update Launch Phase section to remove description texts (see below for reference) <img width="1144" alt="Screenshot 2023-05-23 at 9 47 02 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/e66e20d1-3418-49cd-9028-988c997cfc12">

- [ ] For the Learn More Section, let's collapse every other child element when expanding a single one. (i.e., default accordion behaviour in this example: https://flowbite.com/docs/components/accordion/) <img width="1141" alt="Screenshot 2023-05-23 at 9 56 09 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/2ebdd426-1c51-44d3-bae5-eae05e598029">
- [ ] If possible, add _indent_ to bullet points (see above image). 

- [ ] Update margins for below sections to `60px` decrease the height of each section: Introduction Section, Features Section, Participation Mechanics Section, Launch Phases Section, Get Involved Section.
- [ ] Update Gap for Features Section to `24px`

**Comment by monaiuu** [comment]
Notes for @thomivy 

- For the TSS section, I will create a separate issue to tackle this in upcoming sprint (see [issue](https://github.com/webb-tools/webb-experiences/issues/158))
- This section looks abit odd after removing the Github component, any idea what we could potentially replace it with? <img width="1221" alt="Screenshot 2023-05-23 at 10 37 32 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/4d186986-aad1-4038-bc77-07086db5e091">

**Comment by drewstone** [comment]
@vutuanlinh2k2 are all of these items addressed? The issue is still open so just checking.

**Comment by vutuanlinh2k2** [comment]
@drewstone yes I have fixed all of the above problems.

**Comment by AtelyPham** [comment]
Close as completed (check the the deployment [here](https://develop--tangle-webbsite.netlify.app/)).
