### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by chinh752** [webb-tools/webb-dapp#1265]
## Steps to Reproduce

1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by chinh752** [comment]
![image](https://github.com/webb-tools/webb-dapp/assets/130378676/ea9a6434-7bf1-4cbd-87ed-fccdc271327f)

**Comment by AtelyPham** [comment]
Hello, @chinh752! Thank you for opening the issue. In order to assist you more effectively, could you please provide us with some additional information on this issue? 
- How did you come across this error? 
- Could you please outline the steps to reproduce the problem? 
- What is the output displayed on the browser console?
This information will be extremely helpful in allowing us to identify and resolve the issue.
