### ISSUE TITLE
[BUG] Handle when User Has Insufficient Disk Space to Store Cached Fixtures

### ISSUE THREAD

**Issue by mehdisky99** [webb-tools/webb-dapp#1269]
### Possible Solution
Transaction Failed

## Steps to Reproduce
https://app.webb.tools/#/bridge
webb://v1:vanchor/1099522782887:1099512049389/0x38e7aa90c77f86747fab355eecaa0c2e4c3a463d:0x38e7aa90c77f86747fab355eecaa0c2e4c3a463d/0000010000066eed:00000000000000000000000000000000000000000000000000b1a2bc2ec50000:043e87c2dcc5ba6a6b89568976d4a00429ad420b6a86bc7be2150f968b472df4:00072fdd60ce9130e9c079e7a6ac9f188d318d1e2138efa3495f5359fa2cab86/?curve=Bn254&width=5&exp=5&hf=Poseidon&backend=Circom&token=webbAlpha&denom=18&amount=50000000000000000&index=0
1.
2.
3.
4.

### Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

## Context (Environment)

![Screenshot (37)](https://github.com/webb-tools/webb-dapp/assets/79857890/31040693-af82-4f21-9fe4-da8cb567b1fe)

### Browsers Affected

- [x] Chrome= i used this and was problem .
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by mehdisky99** [comment]
I tried several times to bridge tokens but all my transactions are failed .

**Comment by AtelyPham** [comment]
Hello @mehdisky99, thank you for opening the issue. This is because your machine does not have sufficient memory to store the cached fixtures. Please ensure that you have at least 500 MB of free space on your disk and try again. Let me know if you have any further questions. I will address this error and display a clearer message here.
