### ISSUE TITLE
[TASK] Improve sorting display for chains, tokens, and pools lists

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1449]
## Description
Currently, our display of chains, tokens, and pools lacks a systematic order. To improve usability, we should implement a consistent sorting system:

- **Balance-based Sorting** (if applicable): Items with the highest balance should be displayed at the top, as these are most likely to be of immediate interest to users.

- **Alphabetical Sorting**: After sorting by balance, we should sort the list alphabetically to make navigation and identification easier for users. This applies to items with the same balance, as well as those where balance is not applicable.

### Current View
<img width="643" alt="Screenshot 2023-07-18 at 4 15 37 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/5744f1c3-7f6b-4f05-bb86-18a8acff1e7f">

### Improved View
<img width="570" alt="Screenshot 2023-07-18 at 4 22 48 PM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/13351d0a-723b-4a12-8f0a-72b7fc619180">

**Comment by drewstone** [comment]
I'm of the opinion @monaiuu that in order to properly address a better UX here we should redefine what this view looks like. Because in this view we have 2 bridges (those between EVM testnets and those between Orbit testnets) and yet we show them in one cascading list.

I think what's proposed here is overly complex if order is what we want, tracking by balance requires consuming many token balances (unwrapped assets + wrapped, etc.). I think my solution is simple and improves the order with minimal work.
