### ISSUE TITLE
[CHECKLIST] Planning New Feature Integration for the Hubble Bridge

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1520]
This issue outlines a list of features currently not implemented on the Hubble Bridge. Our goal is to plan, prioritize, and execute the integration of these features, spanning both design and code aspects.

- [ ] Integrate address screening on the Hubble Bridge using Chainalysis or TRM
- [x] #1810
- [ ] Reading daily rate limits on deposits & withdrawals and throwing new errors/warnings from the protocol (e.g., maximum of 10,000 tokens per day for deposit/withdrawal)

We welcome your suggestions for additional features that you consider necessary but are currently absent from the Hubble Bridge.

**Comment by drewstone** [comment]
For **Integrate address screening on the Hubble Bridge using Chainalysis or TRM**, we would want to start with a mocked implementation, a fake API of sorts, so that we can quickly plug in an eventual solution. The way it would work is that once a wallet is connected, a request is made to the API service, a response is returned, and from that response a `boolean` value is returned on whether that account is eligible to use the site. If YES, continue, if NO, show an error state and block the user from accessing the site.
