### ISSUE TITLE
Tx hash links to webb.tools; this should be updated.

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#1559]
### Overview

`txhash` in `keys` details page of `stats-dapp` should link to explorer and not to `webb.tools`.

https://github.com/webb-tools/webb-dapp/assets/53374218/ac6094a0-d815-464b-9daa-8edf5975ee31

**Comment by AtelyPham** [comment]
Currently, we can only open a transaction on the PolkadotJS UI if we possess the `block hash`. This is due to the fact that the `transaction hash` is not unique on Substrate, while the `block hash` is unique.

Therefore, my proposed solution is to hide the external link for the `transaction hash` on the UI. Subsequently, we should add an additional `block hash` record along with the `transaction hash` record for the `Key` entity on the backend. This approach ensures that we will have the `block hash` on the front end, enabling us to render the external link to the Polkadot UI.
