### ISSUE TITLE
[BUG] Hubble Stats Overview Page Does Not Update with Latest Data

### ISSUE THREAD

**Issue by AtelyPham** [webb-tools/webb-dapp#1609]
Currently, the Overview Page of Hubble Stats does not update with the latest data. It only displays data from the time of deployment. This issue may be related to the NX project configuration and the Netlify run command. Further investigation is required.

## Expected Behavior
The Overview Page should continuously update with the latest data.

### Current Behavior
The Overview Page only displays data from the time of deployment and does not update with the latest data.

**Comment by AtelyPham** [comment]
After some investigations, the issue comes from the production build of `next.js` on `dist/apps/hubble-stats`, it is not because the Netlify configuration.

To check that, you can run the production build by `yarn next start ./dist/apps/hubble-stats -p 4200`.

**Comment by vutuanlinh2k2** [comment]
The problem with the Overview (Home) Page cannot get the latest data because by default NextJs will take the home page as a static page, not a dynamic page. Need be update Route Config of home page to 'force-dynamic'. 

Next doc to check: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config
