### ISSUE TITLE
[TASK] Implement Top Loading Bar Component

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1621]
## Description
Implement a top loading bar component in across dApps to provide users with a visual indicator of content loading progress. This loading bar should appear at the top of the page, and behave correctly across breakpoints. Additionally, it should be added to Storybook to ensure reusability across the application.

### Screenshot

![Image](https://user-images.githubusercontent.com/109539270/267709645-b46199d6-6b31-4ed8-831d-8f6004d85e48.png)

![Image](https://user-images.githubusercontent.com/109539270/267709696-c9fda167-4984-4353-8798-019b0afe0c90.png)

![Image](https://user-images.githubusercontent.com/109539270/267709578-9fd536aa-75a5-4ee2-86e1-2e5a26160871.png)

**Comment by vutuanlinh2k2** [comment]
For Hubble Stats, we should do the center spinner for Hubble Stats as well. Here are the reasons:

- The Spinner is already being applied in the Bridge and DKG Stats, so it will be much quicker to also use that in Hubble Stats compared to updating to use the loading bar in all the 3 dapps
- The Spinner is more suited for the Bridge and DKG Stats since they are Single-Page-Application (the layout remains the same while we show the spinner while loading the main components based on what users want to see). To keep everything consistent between dapps I think Hubble Stats should follow this as well.

A new issue was created to handle the loading indicator: #1646
