### ISSUE TITLE
[TASK] Hubble Stats Data should be updated and refetched in the background

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#1628]
Currently, the data for both the home page and pool detail page is cached for one hour (according to NextJS doc), resulting in the UI is not updated up-to-date with the back-end when users navigate around. Each page should perform data refetching every 5 seconds. 

Current behavior:
Home page -> Detail Page -> go back to Home page but data is not updated on home page

Expected behavior:
Home page -> Detail Page -> go back to homepage, the data is updated up-to-date

**Comment by vutuanlinh2k2** [comment]
@drewstone let me know if this task resolves the problem you mentioned during the demo about updating the data in the background. Also I find 5 seconds is good enough to get the latest data. Let me know if you suggest a different time interval to refetch data from the backend.

**Comment by drewstone** [comment]
Yes, another framing is to see if the graphQL system can hook into a reactive API. Then you can consume data from subscriptions to the API rather than timing queries. Updating every 5,10 seconds is good. We can also consider only updating what's actively in view and not everything (say in the future if there are lots of pools being tracked). These types of thoughts and trade offs should be considered.

**Comment by AtelyPham** [comment]
Some useful docs for this issue:
- [@live queries in graph-client](https://github.com/graphprotocol/graph-client/blob/main/docs/live.md)
- [The Graph Client Architecture](https://github.com/graphprotocol/graph-client/blob/main/docs/architecture.md)
