### ISSUE TITLE
[TASK] Update DKG stats favicon

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#1644]
### Overview

Currently the DKG stats-dapp favicon is smaller compared to the favicon used in https://www.tangle.tools/. We need to match the size of favicons across all the tangle applications.

![CleanShot 2023-09-21 at 04 44 00](https://github.com/webb-tools/webb-dapp/assets/53374218/53184a40-eec9-4282-97b0-413ee0993f0a)

**Comment by AtelyPham** [comment]
@devpavan04 has set up the TNT logo as the favicon on both the development site and the production site:

- https://stats-dev.tangle.tools
- https://stats.tangle.tools

The only problem at the moment is that the favicon sizes differ between the DKG Stats and Tangle Marketing Site. This discrepancy is likely due to the different technologies we use for these apps. DKG Stats employs React while the Tangle Marketing Site uses Webflow, leading to incompatibility. We need to investigate this further, @devpavan04.

**Comment by drewstone** [comment]
Ok, tried to add a lot more favicons and didn't change the size. So gonna link a PR and we can close this if we want to merge that or even close that.
