### ISSUE TITLE
[FEAT] Create a note account from the wallet/account UI

### ISSUE THREAD

**Issue by shekohex** [webb-tools/webb-dapp#1692]
### Overview

As a user, I want to be able to create a note account without going through the deposit component first. The main use case is that If I setup a new device/browser and set up my wallet; I need to import/sync my notes so I can withdraw them or do a transfer.

### Screenshot

![image](https://github.com/webb-tools/webb-dapp/assets/14620076/8fb4778b-f1d3-42ca-bd4f-a127e006329a)

### Suggested Workflow

The `Sync Notes` button does not work if I do not have a Note account, which is the correct behavior. What I suggest instead of it showing `Sync Notes` it shows `Create a note account` as I do not have one already. Then once I do, it can now show `Sync Notes` or I can go ahead and Import mine manually. 

- When I don't have a note account, disable or don't show "Sync Notes"
- When I don't have a note account, show "Create note account"

**Comment by drewstone** [comment]
For importing accounts, we should consider more complex behaviour which currently isn't supported.
1. If I import notes, because notes have private keys on them, they are spendable. These notes might be from _different_ note accounts and maybe _be different_ from the active note account. This shouldn't stop the user from spending them because that would be kind of annoying and pointless if you're switching devices.
2. We should consider supporting a multi-account system in the app, so that if people import notes from different note accounts they can still spend them. There would still be a _default_ note account which _new notes_ generate with. We would need to think through if this should change the UI at all (as @monaiuu is considering with MASP integration) or if not. Generally speaking, since the private key is on the note, having it in my wallet (even if notes have different keys) is still spendable by that user.

**Comment by monaiuu** [comment]
Agreed. Let's remove add a variant to the account component if the system does not detect a note account with the connected wallet. In this component, user can create a note account with `Create Account` button. User can also learn more about note account by selecting `Learn More` directing user to Hubble [Usage Guide ](https://docs.webb.tools/docs/projects/hubble-bridge/usage-guide/account/)on Note Account.

### [Figma Link](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?type=design&node-id=1834%3A18286&mode=dev)

### Screenshot
<img width="1347" alt="Screenshot 2023-09-28 at 11 08 18 AM" src="https://github.com/webb-tools/webb-dapp/assets/109539270/e40a8739-3581-479d-85b1-be1975081478">
