### ISSUE TITLE
[FEAT] Import multiple notes at once (with review)

### ISSUE THREAD

**Issue by shekohex** [webb-tools/webb-dapp#1693]
### Overview

As a user I want to import multiple notes at one go, instead of one at a time from my file explorer.

**Comment by drewstone** [comment]
For importing accounts, we should consider more complex behaviour which currently isn't supported.

- If I import notes, because notes have private keys on them, they are spendable. These notes might be from different note accounts and maybe be different from the active note account. This shouldn't stop the user from spending them because that would be kind of annoying and pointless if you're switching devices.
- We should consider supporting a multi-account system in the app, so that if people import notes from different note accounts they can still spend them. There would still be a default note account which new notes generate with. We would need to think through if this should change the UI at all (as @monaiuu is considering with MASP integration) or if not. Generally speaking, since the private key is on the note, having it in my wallet (even if notes have different keys) is still spendable by that user.

**Comment by AtelyPham** [comment]
Did you mean this feature, @shekohex? It is already supported on the dApp, and it will be migrated to the note account soon.

https://github.com/webb-tools/webb-dapp/assets/60747384/42fc252c-a44d-44a0-b872-f96d94ddec79

**Comment by drewstone** [comment]
Yes I think we did, we can revisit this once the account page is finished since ideally it'll be improved by then. Thanks for sharing the video @AtelyPham. Also I think what led Shady here was a lack of redundancy in the original account pop-down. Redundancy is good when we see ourselves (or our users) expect functionality where it seems to make sense. If this seems apparent as we build out the account page we should add it redundantly.
