### ISSUE TITLE
[TASK] Removal of Chain Selection Option in Withdrawal Flow on Destination Input

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1700]
## Description
Given that users can only withdraw on the chain where the token is located, the ability to select a chain in the destination input is unnecessary and could lead to misunderstandings. To eliminate potential user confusion in the withdrawal flow, this task entails **_removing_** the `chevron-down` selector associated with the destination input's chain selection, so that user **_cannot_** interact with chain selection in destination input. 

### Screenshot

![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/bdddaec4-2b45-4c88-a46c-ff62573a7db4)

**Comment by drewstone** [comment]
Well to the contrary, the destination chain _could be used to select where any change amount assets are spendable_. This would be nice to actually include and explain because it is functionality that is entirely possible. I could withdraw funds on polygon and the change amounts get re-inserted to be spent on Arbitrum (withdraw and bridge at the same time).

I honestly propose that we integrate that functionality instead of removing this. Wdyt @monaiuu ?

**Comment by monaiuu** [comment]
@drewstone let's address it in a separate issue; enabling the destination chain input directly since currently it displays the withdrawal amount not the change amount. User would mistaken the withdrawal amount going to a new destination chain, rather than the change amount.
