### ISSUE TITLE
[TASK] Update Display for Zero Balance in Select Token Card

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1710]
## Description
In the current implementation, when a user has no balance for a specific token in the Select Token Card, a warning badge is displayed with a hover tooltip indicating no balance. To align with the display conventions of most bridges, let's update to simply display '`0`' to indicate no balance, instead of using a warning badge.

In addition, we should update the sorting order of tokens based on their balance, from highest to lowest (`0`), aligning with common practices in other bridges. 

Above sorting mechanism issue can be addressed here: https://github.com/webb-tools/webb-dapp/issues/1449

### Screenshot
![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/688d8f99-01dd-4567-b760-e83d6e087799)

![Image](https://github.com/webb-tools/webb-dapp/assets/109539270/69ebafe6-f82a-40af-aae1-140d78b2b13e)

Note: we can use the badge variant to indicate anomaly states. For instance, a warning badge can be used to signal low liquidity for the shielded pool during the unwrapping flow.

**Comment by drewstone** [comment]
Agreed, these types of states as I'm seeing stem from a large use of `undefined`s in the code as well. I know I've said a couple of times, but I'm very much against `undefined` states on front-end apps. @AtelyPham @vutuanlinh2k2 @devpavan04 I generally recommend avoiding these and I would encourage us to think of smarter ways to deal with the `undefined` case. For example, it does seem odd we have used `undefined` for balances rather than 0. Did you guys forget that 0 is a number?
