### ISSUE TITLE
[FEAT] Shared Profile Update Flow

### ISSUE THREAD

**Issue by monaiuu** [webb-tools/webb-dapp#1993]
## Description
Users who have initially set up their profile with shared restaking need the ability to update their profile. This task involves creating a user interface and logic to adjust the total restake amount and to add or remove roles, taking into account the activity status of each service role.

### Key Points:
- **Increasing Total Restake**:
    - [x] Users can increase the total restaked amount across all roles, regardless if there are active services or not.
- **Decreasing Total Restake**:
    - [x] Decreasing the total restaked amount is not allowed if there are active services. Ensures committed resources for ongoing services are not reduced.
- **Removing Inactive Roles**:
    - [x] Users can remove roles that are inactive.
    - [x] Users cannot remove roles that are currently active (locked up).
- **Adding New Roles**:
    - [x] Users can add new roles to their shared profile.
        - [x] The total restaked amount must cover the minimum required for the new roles added.

### [Additional Notes](https://www.notion.so/hicommonwealth/Design-Review-ca92d31516a44d6dad245ba0d0be06a9?pvs=4)

**Comment by yurixander** [comment]
I changed the implementation a bit from the design, I think this method is simpler. Let me know your thoughts! @monaiuu

* Roles that can be removed have the `X` next to them, and are unlocked in the dropdown.
* If there are roles with active jobs, the lock & tooltip will be displayed, otherwise it will remain hidden.

![image](https://github.com/webb-tools/webb-dapp/assets/101931215/2c2980a7-32d6-400b-830c-2e106a4025cd)

**Comment by monaiuu** [comment]
Makes sense, thanks for the heads up!
