### ISSUE TITLE
[TASK] Integrate back-end on InfoCard on Service Details page

### ISSUE THREAD

**Issue by vutuanlinh2k2** [webb-tools/webb-dapp#2063]
### Description
Fetch data to display service type, threshold, key, start and end date. This must be done with `GraphQL` since **polkadot** `storage` does not store timestamps when a service is created

![Image](https://github.com/webb-tools/webb-dapp/assets/69841784/fd770d89-ea90-4f41-8cb8-be22504eb21f)

**Comment by drewstone** [comment]
If you have the block the service was created at, say 1000000, then _if you know when the chain started and with a block time of 6 seconds_ you can find out when this service started.

**Comment by yurixander** [comment]
There's a constant on Substrate/Polkadot API you can use to obtain the expected block time in ms which may be preferable than hard-coding the value as 6s (see screenshot).

Apart from that, it should be noted that since blocks aren't always exactly 6s, it really is an estimate. So on the 'End' field, or somewhere, it would be a good idea to let the users know that it is an estimate rather than an exact timing.

![image](https://github.com/webb-tools/webb-dapp/assets/101931215/154a1565-0543-453f-9e81-c83195b5018c)
