### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Page switching performance is slow

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2126]
# Overview
When I click, I want to go to that page not wait.
https://www.loom.com/share/d1a79031bb814c7a9372fb35993a3ac0?sid=d480a95f-8f11-4448-8dfd-7a6fa92f0837

**Comment by vutuanlinh2k2** [comment]
Navigating between pages is slow because  of data loading from the server is heavy. 

One way to fix this is to to create loading screen for the pages when the data is fetching. This feature already provided by Next.js [here](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming). 

I will implement this in 3 pages: Home (Account), Nomination and Claim since the Service Overview and Restake pages will most likely be hidden when launching

Here is an simple example (the page is load instantly when navigating):

https://github.com/webb-tools/webb-dapp/assets/69841784/0617ea57-e03e-42e1-875a-247d49751f38
