### ISSUE TITLE
[TASK] 🚀 Pre-launch audit: Payouts audit

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2152]
- [x] Ensure that payouts work, currently the table is not showing up even though there are payouts. It is currently throwing an error about something being undefined.
- [x] Ensure that there aren't any problems with caching (ie. try reloading page, changing networks, etc. and check that always the proper values are displayed)
- [x] Re-work calculations after runtime upgrade, use newer non-deprecated Substrate query APIs

**Comment by vutuanlinh2k2** [comment]
@yurixander

### Description 
After switching chain, the Payouts table still displays data from the previous chain. This is because the data for the table is still stored in Local Storage. The data is cached for both Payouts and Nominations table but the Nominations table still has the correct behavior somehow.

### Recording
https://github.com/webb-tools/webb-dapp/assets/69841784/25f8164b-9a50-404e-bb31-e83b7b967637
