### ISSUE TITLE
[TASK] Batch all substrate calls (and all EVM calls possible)

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb-dapp#2226]
# Overview
On the nomination page of Tangle dApp we don't seem to be leveraging `utility.batchAll` enough to batch calls to save transaction fees. This should be done for every possible flow.

### List of calls (not exhaustive)
- [x] Nominate (bond and set validator prefs)
- [x] Payouts (payout for as many eras)

**Comment by yurixander** [comment]
Note: Transaction batching was implemented on https://github.com/webb-tools/webb-dapp/pull/2189 for all appropriate transactions that use it (ie. setup nominator, payout stakers), but waiting for the [payouts PR](https://github.com/webb-tools/webb-dapp/pull/2241) to be merged in order to test it with the new/updated payouts functionality.

**Comment by drewstone** [comment]
Reassigned to you @devpavan04

**Comment by devpavan04** [comment]
Closing this issue as it has been implemented in PR #2189 and tested successfully in PR #2335.

**Comment by yurixander** [comment]
Will be testing this briefly and then it's ready to close.
