### ISSUE TITLE
Modularity enhancement in terms of features not the API naming conventions

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb-dapp#44]
**Is your feature request related to a problem? Please describe.**
It is more modular to have every feature`s related code on a module (Folder), Instead of having the contexts on a module, hooks for a module ...etc

instead, a better structure may look like

<pre>
react-environment
├── api
│   └── hooks
|	|	└── use-api.hook.ts
|	└── interfaces
|	|	└── api.interface.ts
|	└── utis
|	|	└── ...
|	└── index.ts
└── shared
|   └── hooks
|	|    └── ...
|   └── utils
|   |	└── ...
|	└── index.ts

</pre>

**Comment by drewstone** [comment]
I think it is better to have each individual folder, specific to the function (such as hooks), because it makes exporting those packages a lot more well-rounded.

For example, if a new dapp wanted to use our hooks or a future project of ours, then instead of consuming many dependencies for each individual hook they'd need (mixer, calls, etc.) they can consume 1.

**Comment by drewstone** [comment]
I also think the structure is also more easy to learn, although it may be annoying. It's actually clear where all the hooks are if I'm curious about the code of one. Or similarly, what the page for the mixer looks like and where the UI code for that is housed.
