### ISSUE TITLE
[BUG] Best and Finalized block chips in stats dApp do not update with custom endpoint

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb-dapp#798]
## Overview

If you set a custom data source endpoint, the current implementation does not reflect those changes in the best and finalized block chips:

![Screen Shot 2022-12-09 at 11 58 15 AM](https://user-images.githubusercontent.com/29983536/206763988-c2c197cb-1363-4bb5-97b3-122373066a3c.png)

### Expected behaviour 

If the subquery endpoint is changed, the api in which we are fetching best and finalized block needs to reflect that change. 

#### To reproduce
1. Update default endpoint to use `https://tangle-subquery.webb.tools/graphql` in custom data source input (you can also use localhost and point to local network)
2. Go to [polkadot.js explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftangle-archive.webb.tools%2F#/explorer) for the archive node to see best and finalized block 
3. Compare what it is being reported there and on the stats dapp

**Comment by devpavan04** [comment]
**Custom Data Source will not update the best and finalized block chips because we are using two different data sources in the current implementation.**

1. `Subquery endpoint` for all the stats
2. `Explorer endpoint` for just retrieving  `best` and `finalized` blocks

To resolve this we need the user to enter `Explorer endpoint` along with `Subquery endpoint`

**Example:**

Subquery endpoint: `https://subquery-dev.webb.tools/graphql`
Explorer endpoint: `wss://arana-alpha-1.webb.tools/`

Need design update which allows the user to input both `Subquery endpoint` and `Explorer endpoint` for this issue to be resolved.

**Comment by monaiuu** [comment]
@dutterbutter @devpavan04 just came across this thread, is design update still required?

**Comment by devpavan04** [comment]
@monaiuu Yes we need a design update. This issue was closed with a temporary fix. I'll open a new issue explaining the design update requirements.

**Comment by monaiuu** [comment]
@devpavan04 sounds good, thank you!
