### ISSUE TITLE
[BUG] Unable to select moonbase alpha DEV tokens for depositing

### ISSUE THREAD

**Issue by devpavan04** [webb-tools/webb-dapp#940]
### Overview
Token selection component does not display DEV tokens to be selected for depositing.

### Issue video

https://user-images.githubusercontent.com/53374218/215357461-6e8dba85-a772-48b8-9b80-ded09d23f32f.mov

**Comment by AtelyPham** [comment]
I've checked this issue, this also occurs in Mumbai. Because the fungibleToken does not allow the native token on Moonbase Alpha and Mumbai, you can check it [here](https://github.com/webb-tools/webb-dapp/blob/develop/libs/web3-api-provider/src/webb-provider/bridge-api.ts#L74).

cc: @dutterbutter @drewstone.

**Comment by dutterbutter** [comment]
Closed in #985
